run:
  timeout: 5m
  go: "1.21"

linters-settings:
  govet:
    enable:
      - shadow
  dupl:
    threshold: 200 # Very lenient for existing code
  lll:
    line-length: 200 # Very lenient

linters:
  enable:
    # Only enable the most critical linters for CI
    - errcheck    # Check error handling
    - govet       # Go vet tool
    - ineffassign # Detect ineffectual assignments
    - staticcheck # Advanced Go analysis
    - typecheck   # Type checking
    - unused      # Find unused code
    - gosimple    # Simplify code
    - gofmt       # Ensure proper formatting

  disable-all: false

issues:
  exclude-use-default: true

  # Be very lenient with issues
  max-issues-per-linter: 50
  max-same-issues: 10

  exclude:
    # Ignore common patterns in existing code
    - "Error return value.*is not checked"
    - "ST1000:"
    - "ST1020:"
    - "`.*` is unused"
    - "duplicate"