version: "2"
run:
  go: "1.25"
linters:
  settings:
    dupl:
      threshold: 200
    govet:
      enable:
        - shadow
    lll:
      line-length: 200
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: Error return value.*is not checked
      - path: (.+)\.go$
        text: 'ST1000:'
      - path: (.+)\.go$
        text: 'ST1020:'
      - path: (.+)\.go$
        text: '`.*` is unused'
      - path: (.+)\.go$
        text: duplicate
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
